INSERT INTO public.campuses (name, city, state, country, domain, status) VALUES
('University of Alabama','Tuscaloosa','AL','US','ua.edu','active'),
('Auburn University','Auburn','AL','US','auburn.edu','active'),
('University of Alaska Anchorage','Anchorage','AK','US','uaa.alaska.edu','active'),
('Arizona State University','Tempe','AZ','US','asu.edu','active'),
('University of Arizona','Tucson','AZ','US','arizona.edu','active'),
('University of Arkansas','Fayetteville','AR','US','uark.edu','active'),
('UCLA','Los Angeles','CA','US','ucla.edu','active'),
('UC Berkeley','Berkeley','CA','US','berkeley.edu','active'),
('UC San Diego','La Jolla','CA','US','ucsd.edu','active'),
('UC Davis','Davis','CA','US','ucdavis.edu','active'),
('UC Irvine','Irvine','CA','US','uci.edu','active'),
('UC Santa Barbara','Santa Barbara','CA','US','ucsb.edu','active'),
('UC Santa Cruz','Santa Cruz','CA','US','ucsc.edu','active'),
('UC Riverside','Riverside','CA','US','ucr.edu','active'),
('Stanford University','Stanford','CA','US','stanford.edu','active'),
('USC','Los Angeles','CA','US','usc.edu','active'),
('San Diego State University','San Diego','CA','US','sdsu.edu','active'),
('Cal Poly San Luis Obispo','San Luis Obispo','CA','US','calpoly.edu','active'),
('San Jose State University','San Jose','CA','US','sjsu.edu','active'),
('CSU Long Beach','Long Beach','CA','US','csulb.edu','active'),
('CSU Fullerton','Fullerton','CA','US','fullerton.edu','active'),
('San Francisco State University','San Francisco','CA','US','sfsu.edu','active'),
('Cal State Northridge','Northridge','CA','US','csun.edu','active'),
('Fresno State','Fresno','CA','US','csufresno.edu','active'),
('Sacramento State','Sacramento','CA','US','csus.edu','active'),
('Santa Clara University','Santa Clara','CA','US','scu.edu','active'),
('Loyola Marymount University','Los Angeles','CA','US','lmu.edu','active'),
('University of Colorado Boulder','Boulder','CO','US','colorado.edu','active'),
('Colorado State University','Fort Collins','CO','US','colostate.edu','active'),
('University of Denver','Denver','CO','US','du.edu','active'),
('University of Connecticut','Storrs','CT','US','uconn.edu','active'),
('Yale University','New Haven','CT','US','yale.edu','active'),
('University of Delaware','Newark','DE','US','udel.edu','active'),
('Georgetown University','Washington','DC','US','georgetown.edu','active'),
('George Washington University','Washington','DC','US','gwu.edu','active'),
('American University','Washington','DC','US','american.edu','active'),
('Howard University','Washington','DC','US','howard.edu','active'),
('University of Florida','Gainesville','FL','US','ufl.edu','active'),
('Florida State University','Tallahassee','FL','US','fsu.edu','active'),
('University of Central Florida','Orlando','FL','US','ucf.edu','active'),
('University of South Florida','Tampa','FL','US','usf.edu','active'),
('Florida International University','Miami','FL','US','fiu.edu','active'),
('University of Miami','Coral Gables','FL','US','miami.edu','active'),
('University of Georgia','Athens','GA','US','uga.edu','active'),
('Georgia Tech','Atlanta','GA','US','gatech.edu','active'),
('Georgia State University','Atlanta','GA','US','gsu.edu','active'),
('Emory University','Atlanta','GA','US','emory.edu','active'),
('University of Hawaii at Manoa','Honolulu','HI','US','hawaii.edu','active'),
('Boise State University','Boise','ID','US','boisestate.edu','active'),
('University of Illinois Urbana-Champaign','Champaign','IL','US','illinois.edu','active'),
('Northwestern University','Evanston','IL','US','northwestern.edu','active'),
('University of Chicago','Chicago','IL','US','uchicago.edu','active'),
('DePaul University','Chicago','IL','US','depaul.edu','active'),
('Indiana University Bloomington','Bloomington','IN','US','indiana.edu','active'),
('Purdue University','West Lafayette','IN','US','purdue.edu','active'),
('University of Notre Dame','Notre Dame','IN','US','nd.edu','active'),
('University of Iowa','Iowa City','IA','US','uiowa.edu','active'),
('Iowa State University','Ames','IA','US','iastate.edu','active'),
('University of Kansas','Lawrence','KS','US','ku.edu','active'),
('Kansas State University','Manhattan','KS','US','ksu.edu','active'),
('University of Kentucky','Lexington','KY','US','uky.edu','active'),
('University of Louisville','Louisville','KY','US','louisville.edu','active'),
('Louisiana State University','Baton Rouge','LA','US','lsu.edu','active'),
('Tulane University','New Orleans','LA','US','tulane.edu','active'),
('University of Maryland','College Park','MD','US','umd.edu','active'),
('Johns Hopkins University','Baltimore','MD','US','jhu.edu','active'),
('MIT','Cambridge','MA','US','mit.edu','active'),
('Harvard University','Cambridge','MA','US','harvard.edu','active'),
('Boston University','Boston','MA','US','bu.edu','active'),
('Northeastern University','Boston','MA','US','northeastern.edu','active'),
('University of Massachusetts Amherst','Amherst','MA','US','umass.edu','active'),
('University of Michigan','Ann Arbor','MI','US','umich.edu','active'),
('Michigan State University','East Lansing','MI','US','msu.edu','active'),
('Wayne State University','Detroit','MI','US','wayne.edu','active'),
('University of Minnesota','Minneapolis','MN','US','umn.edu','active'),
('University of Mississippi','Oxford','MS','US','olemiss.edu','active'),
('Mississippi State University','Starkville','MS','US','msstate.edu','active'),
('University of Missouri','Columbia','MO','US','missouri.edu','active'),
('Washington University in St. Louis','St. Louis','MO','US','wustl.edu','active'),
('University of Montana','Missoula','MT','US','umt.edu','active'),
('University of Nebraska-Lincoln','Lincoln','NE','US','unl.edu','active'),
('Creighton University','Omaha','NE','US','creighton.edu','active'),
('UNLV','Las Vegas','NV','US','unlv.edu','active'),
('University of Nevada Reno','Reno','NV','US','unr.edu','active'),
('University of New Hampshire','Durham','NH','US','unh.edu','active'),
('Dartmouth College','Hanover','NH','US','dartmouth.edu','active'),
('Rutgers University','New Brunswick','NJ','US','rutgers.edu','active'),
('Princeton University','Princeton','NJ','US','princeton.edu','active'),
('University of New Mexico','Albuquerque','NM','US','unm.edu','active'),
('New Mexico State University','Las Cruces','NM','US','nmsu.edu','active'),
('NYU','New York','NY','US','nyu.edu','active'),
('Columbia University','New York','NY','US','columbia.edu','active'),
('Cornell University','Ithaca','NY','US','cornell.edu','active'),
('SUNY Buffalo','Buffalo','NY','US','buffalo.edu','active'),
('SUNY Stony Brook','Stony Brook','NY','US','stonybrook.edu','active'),
('Syracuse University','Syracuse','NY','US','syr.edu','active'),
('UNC Chapel Hill','Chapel Hill','NC','US','unc.edu','active'),
('NC State','Raleigh','NC','US','ncsu.edu','active'),
('Duke University','Durham','NC','US','duke.edu','active'),
('Wake Forest University','Winston-Salem','NC','US','wfu.edu','active'),
('North Dakota State University','Fargo','ND','US','ndsu.edu','active'),
('Ohio State University','Columbus','OH','US','osu.edu','active'),
('University of Cincinnati','Cincinnati','OH','US','uc.edu','active'),
('Case Western Reserve University','Cleveland','OH','US','case.edu','active'),
('University of Oklahoma','Norman','OK','US','ou.edu','active'),
('Oklahoma State University','Stillwater','OK','US','okstate.edu','active'),
('University of Oregon','Eugene','OR','US','uoregon.edu','active'),
('Oregon State University','Corvallis','OR','US','oregonstate.edu','active'),
('Portland State University','Portland','OR','US','pdx.edu','active'),
('Penn State','University Park','PA','US','psu.edu','active'),
('University of Pennsylvania','Philadelphia','PA','US','upenn.edu','active'),
('University of Pittsburgh','Pittsburgh','PA','US','pitt.edu','active'),
('Carnegie Mellon University','Pittsburgh','PA','US','cmu.edu','active'),
('Temple University','Philadelphia','PA','US','temple.edu','active'),
('Drexel University','Philadelphia','PA','US','drexel.edu','active'),
('Villanova University','Villanova','PA','US','villanova.edu','active'),
('University of Rhode Island','Kingston','RI','US','uri.edu','active'),
('Brown University','Providence','RI','US','brown.edu','active'),
('Clemson University','Clemson','SC','US','clemson.edu','active'),
('University of South Carolina','Columbia','SC','US','sc.edu','active'),
('University of South Dakota','Vermillion','SD','US','usd.edu','active'),
('University of Tennessee','Knoxville','TN','US','utk.edu','active'),
('Vanderbilt University','Nashville','TN','US','vanderbilt.edu','active'),
('University of Memphis','Memphis','TN','US','memphis.edu','active'),
('University of Texas at Austin','Austin','TX','US','utexas.edu','active'),
('Texas A&M University','College Station','TX','US','tamu.edu','active'),
('Texas Tech University','Lubbock','TX','US','ttu.edu','active'),
('University of Houston','Houston','TX','US','uh.edu','active'),
('Rice University','Houston','TX','US','rice.edu','active'),
('UT Dallas','Richardson','TX','US','utdallas.edu','active'),
('UT San Antonio','San Antonio','TX','US','utsa.edu','active'),
('UT Arlington','Arlington','TX','US','uta.edu','active'),
('SMU','Dallas','TX','US','smu.edu','active'),
('TCU','Fort Worth','TX','US','tcu.edu','active'),
('Baylor University','Waco','TX','US','baylor.edu','active'),
('University of Utah','Salt Lake City','UT','US','utah.edu','active'),
('Brigham Young University','Provo','UT','US','byu.edu','active'),
('University of Vermont','Burlington','VT','US','uvm.edu','active'),
('University of Virginia','Charlottesville','VA','US','virginia.edu','active'),
('Virginia Tech','Blacksburg','VA','US','vt.edu','active'),
('George Mason University','Fairfax','VA','US','gmu.edu','active'),
('Virginia Commonwealth University','Richmond','VA','US','vcu.edu','active'),
('Old Dominion University','Norfolk','VA','US','odu.edu','active'),
('University of Washington','Seattle','WA','US','uw.edu','active'),
('Washington State University','Pullman','WA','US','wsu.edu','active'),
('Gonzaga University','Spokane','WA','US','gonzaga.edu','active'),
('West Virginia University','Morgantown','WV','US','wvu.edu','active'),
('University of Wisconsin-Madison','Madison','WI','US','wisc.edu','active'),
('Marquette University','Milwaukee','WI','US','marquette.edu','active'),
('University of Wyoming','Laramie','WY','US','uwyo.edu','active'),
('University of South Alabama','Mobile','AL','US','southalabama.edu','active');