INSERT INTO public.campuses (name, city, state, country, domain, status) VALUES
-- HBCUs
('Spelman College','Atlanta','GA','US','spelman.edu','active'),
('Morehouse College','Atlanta','GA','US','morehouse.edu','active'),
('Tuskegee University','Tuskegee','AL','US','tuskegee.edu','active'),
('Hampton University','Hampton','VA','US','hamptonu.edu','active'),
('Florida A&M University','Tallahassee','FL','US','famu.edu','active'),
('North Carolina A&T','Greensboro','NC','US','ncat.edu','active'),
('North Carolina Central University','Durham','NC','US','nccu.edu','active'),
('Tennessee State University','Nashville','TN','US','tnstate.edu','active'),
('Jackson State University','Jackson','MS','US','jsums.edu','active'),
('Southern University','Baton Rouge','LA','US','subr.edu','active'),
('Prairie View A&M University','Prairie View','TX','US','pvamu.edu','active'),
('Texas Southern University','Houston','TX','US','tsu.edu','active'),
('Morgan State University','Baltimore','MD','US','morgan.edu','active'),
('Grambling State University','Grambling','LA','US','gram.edu','active'),
('Bethune-Cookman University','Daytona Beach','FL','US','cookman.edu','active'),
('Clark Atlanta University','Atlanta','GA','US','cau.edu','active'),
('Fisk University','Nashville','TN','US','fisk.edu','active'),
('Xavier University of Louisiana','New Orleans','LA','US','xula.edu','active'),
('Norfolk State University','Norfolk','VA','US','nsu.edu','active'),
('Alabama A&M University','Huntsville','AL','US','aamu.edu','active'),
('Alabama State University','Montgomery','AL','US','alasu.edu','active'),
('Delaware State University','Dover','DE','US','desu.edu','active'),
('Bowie State University','Bowie','MD','US','bowiestate.edu','active'),
('Coppin State University','Baltimore','MD','US','coppin.edu','active'),
('Lincoln University','Lincoln University','PA','US','lincoln.edu','active'),
('Alcorn State University','Lorman','MS','US','alcorn.edu','active'),
('South Carolina State University','Orangeburg','SC','US','scsu.edu','active'),
('Savannah State University','Savannah','GA','US','savannahstate.edu','active'),
('Winston-Salem State University','Winston-Salem','NC','US','wssu.edu','active'),
('Langston University','Langston','OK','US','langston.edu','active'),

-- Liberal Arts Colleges
('Williams College','Williamstown','MA','US','williams.edu','active'),
('Amherst College','Amherst','MA','US','amherst.edu','active'),
('Swarthmore College','Swarthmore','PA','US','swarthmore.edu','active'),
('Wellesley College','Wellesley','MA','US','wellesley.edu','active'),
('Pomona College','Claremont','CA','US','pomona.edu','active'),
('Bowdoin College','Brunswick','ME','US','bowdoin.edu','active'),
('Claremont McKenna College','Claremont','CA','US','cmc.edu','active'),
('Middlebury College','Middlebury','VT','US','middlebury.edu','active'),
('Carleton College','Northfield','MN','US','carleton.edu','active'),
('Haverford College','Haverford','PA','US','haverford.edu','active'),
('Vassar College','Poughkeepsie','NY','US','vassar.edu','active'),
('Colby College','Waterville','ME','US','colby.edu','active'),
('Bates College','Lewiston','ME','US','bates.edu','active'),
('Harvey Mudd College','Claremont','CA','US','hmc.edu','active'),
('Grinnell College','Grinnell','IA','US','grinnell.edu','active'),
('Hamilton College','Clinton','NY','US','hamilton.edu','active'),
('Colgate University','Hamilton','NY','US','colgate.edu','active'),
('Oberlin College','Oberlin','OH','US','oberlin.edu','active'),
('Smith College','Northampton','MA','US','smith.edu','active'),
('Wesleyan University','Middletown','CT','US','wesleyan.edu','active'),
('Barnard College','New York','NY','US','barnard.edu','active'),
('Bryn Mawr College','Bryn Mawr','PA','US','brynmawr.edu','active'),
('Mount Holyoke College','South Hadley','MA','US','mtholyoke.edu','active'),
('Reed College','Portland','OR','US','reed.edu','active'),
('Whitman College','Walla Walla','WA','US','whitman.edu','active'),
('Macalester College','St. Paul','MN','US','macalester.edu','active'),
('Kenyon College','Gambier','OH','US','kenyon.edu','active'),
('Bucknell University','Lewisburg','PA','US','bucknell.edu','active'),
('Lafayette College','Easton','PA','US','lafayette.edu','active'),
('Lehigh University','Bethlehem','PA','US','lehigh.edu','active'),
('Trinity College','Hartford','CT','US','trincoll.edu','active'),
('Connecticut College','New London','CT','US','conncoll.edu','active'),
('Scripps College','Claremont','CA','US','scrippscollege.edu','active'),
('Pitzer College','Claremont','CA','US','pitzer.edu','active'),
('Occidental College','Los Angeles','CA','US','oxy.edu','active'),
('Lewis & Clark College','Portland','OR','US','lclark.edu','active'),
('Colorado College','Colorado Springs','CO','US','coloradocollege.edu','active'),
('Sewanee: University of the South','Sewanee','TN','US','sewanee.edu','active'),
('Rhodes College','Memphis','TN','US','rhodes.edu','active'),
('Furman University','Greenville','SC','US','furman.edu','active'),
('Davidson College','Davidson','NC','US','davidson.edu','active'),
('Washington and Lee University','Lexington','VA','US','wlu.edu','active'),
('University of Richmond','Richmond','VA','US','richmond.edu','active'),
('Elon University','Elon','NC','US','elon.edu','active'),
('Rollins College','Winter Park','FL','US','rollins.edu','active'),
('Denison University','Granville','OH','US','denison.edu','active'),
('DePauw University','Greencastle','IN','US','depauw.edu','active'),
('Wabash College','Crawfordsville','IN','US','wabash.edu','active'),
('Beloit College','Beloit','WI','US','beloit.edu','active'),
('Lawrence University','Appleton','WI','US','lawrence.edu','active'),
('St. Olaf College','Northfield','MN','US','stolaf.edu','active'),
('College of Wooster','Wooster','OH','US','wooster.edu','active'),
('Dickinson College','Carlisle','PA','US','dickinson.edu','active'),
('Gettysburg College','Gettysburg','PA','US','gettysburg.edu','active'),
('Franklin & Marshall College','Lancaster','PA','US','fandm.edu','active'),
('Union College','Schenectady','NY','US','union.edu','active'),
('Skidmore College','Saratoga Springs','NY','US','skidmore.edu','active'),
('Sarah Lawrence College','Bronxville','NY','US','sarahlawrence.edu','active'),
('Bennington College','Bennington','VT','US','bennington.edu','active'),

-- Community Colleges
('Santa Monica College','Santa Monica','CA','US','smc.edu','active'),
('De Anza College','Cupertino','CA','US','deanza.edu','active'),
('Foothill College','Los Altos Hills','CA','US','foothill.edu','active'),
('Pasadena City College','Pasadena','CA','US','pasadena.edu','active'),
('Diablo Valley College','Pleasant Hill','CA','US','dvc.edu','active'),
('City College of San Francisco','San Francisco','CA','US','ccsf.edu','active'),
('Los Angeles City College','Los Angeles','CA','US','lacitycollege.edu','active'),
('Glendale Community College','Glendale','CA','US','glendale.edu','active'),
('Orange Coast College','Costa Mesa','CA','US','orangecoastcollege.edu','active'),
('Mt. San Antonio College','Walnut','CA','US','mtsac.edu','active'),
('Miami Dade College','Miami','FL','US','mdc.edu','active'),
('Broward College','Fort Lauderdale','FL','US','broward.edu','active'),
('Valencia College','Orlando','FL','US','valenciacollege.edu','active'),
('Hillsborough Community College','Tampa','FL','US','hccfl.edu','active'),
('Palm Beach State College','Lake Worth','FL','US','palmbeachstate.edu','active'),
('Houston Community College','Houston','TX','US','hccs.edu','active'),
('Dallas College','Dallas','TX','US','dcccd.edu','active'),
('Austin Community College','Austin','TX','US','austincc.edu','active'),
('San Antonio College','San Antonio','TX','US','alamo.edu','active'),
('Tarrant County College','Fort Worth','TX','US','tccd.edu','active'),
('Lone Star College','Houston','TX','US','lonestar.edu','active'),
('Northern Virginia Community College','Annandale','VA','US','nvcc.edu','active'),
('Tidewater Community College','Norfolk','VA','US','tcc.edu','active'),
('Community College of Baltimore County','Baltimore','MD','US','ccbcmd.edu','active'),
('Montgomery College','Rockville','MD','US','montgomerycollege.edu','active'),
('Prince George''s Community College','Largo','MD','US','pgcc.edu','active'),
('Borough of Manhattan Community College','New York','NY','US','bmcc.cuny.edu','active'),
('LaGuardia Community College','Long Island City','NY','US','laguardia.edu','active'),
('Bronx Community College','Bronx','NY','US','bcc.cuny.edu','active'),
('Queensborough Community College','Bayside','NY','US','qcc.cuny.edu','active'),
('Nassau Community College','Garden City','NY','US','ncc.edu','active'),
('Suffolk County Community College','Selden','NY','US','sunysuffolk.edu','active'),
('Community College of Philadelphia','Philadelphia','PA','US','ccp.edu','active'),
('Bucks County Community College','Newtown','PA','US','bucks.edu','active'),
('Cuyahoga Community College','Cleveland','OH','US','tri-c.edu','active'),
('Columbus State Community College','Columbus','OH','US','cscc.edu','active'),
('Sinclair Community College','Dayton','OH','US','sinclair.edu','active'),
('Ivy Tech Community College','Indianapolis','IN','US','ivytech.edu','active'),
('Harper College','Palatine','IL','US','harpercollege.edu','active'),
('College of DuPage','Glen Ellyn','IL','US','cod.edu','active'),
('City Colleges of Chicago','Chicago','IL','US','ccc.edu','active'),
('Maricopa Community Colleges','Tempe','AZ','US','maricopa.edu','active'),
('Pima Community College','Tucson','AZ','US','pima.edu','active'),
('Central Piedmont Community College','Charlotte','NC','US','cpcc.edu','active'),
('Wake Technical Community College','Raleigh','NC','US','waketech.edu','active'),
('Greenville Technical College','Greenville','SC','US','gvltec.edu','active'),
('Chattahoochee Technical College','Marietta','GA','US','chattahoocheetech.edu','active'),
('Georgia Perimeter College','Clarkston','GA','US','gpc.edu','active'),
('Nashville State Community College','Nashville','TN','US','nscc.edu','active'),
('Portland Community College','Portland','OR','US','pcc.edu','active'),
('Bellevue College','Bellevue','WA','US','bellevuecollege.edu','active'),
('Seattle Central College','Seattle','WA','US','seattlecentral.edu','active'),
('Green River College','Auburn','WA','US','greenriver.edu','active'),
('Community College of Denver','Denver','CO','US','ccd.edu','active'),
('Salt Lake Community College','Salt Lake City','UT','US','slcc.edu','active'),
('College of Southern Nevada','Las Vegas','NV','US','csn.edu','active'),
('Bunker Hill Community College','Boston','MA','US','bhcc.edu','active'),
('Manchester Community College','Manchester','CT','US','mcc.edu','active'),
('Bergen Community College','Paramus','NJ','US','bergen.edu','active'),
('County College of Morris','Randolph','NJ','US','ccm.edu','active'),
('Middlesex College','Edison','NJ','US','middlesexcc.edu','active');