INSERT INTO public.campuses (name, city, state, country, domain, status) VALUES
-- Missing HBCUs
('Allen University','Columbia','SC','US','allenuniversity.edu','active'),
('Arkansas Baptist College','Little Rock','AR','US','arkansasbaptist.edu','active'),
('Benedict College','Columbia','SC','US','benedict.edu','active'),
('Bennett College','Greensboro','NC','US','bennett.edu','active'),
('Bluefield State University','Bluefield','WV','US','bluefieldstate.edu','active'),
('Central State University','Wilberforce','OH','US','centralstate.edu','active'),
('Cheyney University','Cheyney','PA','US','cheyney.edu','active'),
('Claflin University','Orangeburg','SC','US','claflin.edu','active'),
('Clinton College','Rock Hill','SC','US','clintoncollege.edu','active'),
('Coahoma Community College','Clarksdale','MS','US','coahomacc.edu','active'),
('Concordia College Alabama','Selma','AL','US','concordiaselma.edu','active'),
('Denmark Technical College','Denmark','SC','US','denmarktech.edu','active'),
('Dillard University','New Orleans','LA','US','dillard.edu','active'),
('Edward Waters University','Jacksonville','FL','US','ewc.edu','active'),
('Elizabeth City State University','Elizabeth City','NC','US','ecsu.edu','active'),
('Fayetteville State University','Fayetteville','NC','US','uncfsu.edu','active'),
('Fort Valley State University','Fort Valley','GA','US','fvsu.edu','active'),
('Gadsden State Community College','Gadsden','AL','US','gadsdenstate.edu','active'),
('Harris-Stowe State University','St. Louis','MO','US','hssu.edu','active'),
('Hinds Community College - Utica','Utica','MS','US','hindscc.edu','active'),
('Huston-Tillotson University','Austin','TX','US','htu.edu','active'),
('Interdenominational Theological Center','Atlanta','GA','US','itc.edu','active'),
('J.F. Drake State Technical College','Huntsville','AL','US','drakestate.edu','active'),
('Jarvis Christian University','Hawkins','TX','US','jarvis.edu','active'),
('Johnson C. Smith University','Charlotte','NC','US','jcsu.edu','active'),
('Kentucky State University','Frankfort','KY','US','kysu.edu','active'),
('Knoxville College','Knoxville','TN','US','knoxvillecollege.edu','active'),
('Lane College','Jackson','TN','US','lanecollege.edu','active'),
('Lawson State Community College','Birmingham','AL','US','lawsonstate.edu','active'),
('Le Moyne-Owen College','Memphis','TN','US','loc.edu','active'),
('Livingstone College','Salisbury','NC','US','livingstone.edu','active'),
('Meharry Medical College','Nashville','TN','US','mmc.edu','active'),
('Miles College','Fairfield','AL','US','miles.edu','active'),
('Mississippi Valley State University','Itta Bena','MS','US','mvsu.edu','active'),
('Morris College','Sumter','SC','US','morris.edu','active'),
('Morris Brown College','Atlanta','GA','US','morrisbrown.edu','active'),
('Oakwood University','Huntsville','AL','US','oakwood.edu','active'),
('Paine College','Augusta','GA','US','paine.edu','active'),
('Paul Quinn College','Dallas','TX','US','pqc.edu','active'),
('Philander Smith University','Little Rock','AR','US','philander.edu','active'),
('Rust College','Holly Springs','MS','US','rustcollege.edu','active'),
('Saint Augustine''s University','Raleigh','NC','US','st-aug.edu','active'),
('Saint Paul''s College','Lawrenceville','VA','US','saintpauls.edu','active'),
('Shaw University','Raleigh','NC','US','shawu.edu','active'),
('Shorter College','North Little Rock','AR','US','shortercollege.edu','active'),
('Simmons College of Kentucky','Louisville','KY','US','simmonscollegeky.edu','active'),
('South Carolina State University','Orangeburg','SC','US','scsu.edu','active'),
('Southern University at New Orleans','New Orleans','LA','US','suno.edu','active'),
('Southern University at Shreveport','Shreveport','LA','US','susla.edu','active'),
('Southwestern Christian College','Terrell','TX','US','swcc.edu','active'),
('Spelman College','Atlanta','GA','US','spelman.edu','active'),
('St. Philip''s College','San Antonio','TX','US','alamo.edu/spc','active'),
('Stillman College','Tuscaloosa','AL','US','stillman.edu','active'),
('Talladega College','Talladega','AL','US','talladega.edu','active'),
('Tennessee State University','Nashville','TN','US','tnstate.edu','active'),
('Texas College','Tyler','TX','US','texascollege.edu','active'),
('Tougaloo College','Tougaloo','MS','US','tougaloo.edu','active'),
('Trenholm State Community College','Montgomery','AL','US','trenholmstate.edu','active'),
('University of Arkansas at Pine Bluff','Pine Bluff','AR','US','uapb.edu','active'),
('University of Maryland Eastern Shore','Princess Anne','MD','US','umes.edu','active'),
('University of the District of Columbia','Washington','DC','US','udc.edu','active'),
('University of the Virgin Islands','Charlotte Amalie','VI','US','uvi.edu','active'),
('Virginia State University','Petersburg','VA','US','vsu.edu','active'),
('Virginia Union University','Richmond','VA','US','vuu.edu','active'),
('Voorhees University','Denmark','SC','US','voorhees.edu','active'),
('West Virginia State University','Institute','WV','US','wvstateu.edu','active'),
('Wilberforce University','Wilberforce','OH','US','wilberforce.edu','active'),
('Wiley University','Marshall','TX','US','wileyc.edu','active'),
('Winston-Salem State University','Winston-Salem','NC','US','wssu.edu','active'),
('Xavier University of Louisiana','New Orleans','LA','US','xula.edu','active')
ON CONFLICT DO NOTHING;